# Generated by Django 4.0.3 on 2022-03-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desription',
            new_name='desciption',
        ),
    ]
