# Generated by Django 4.0.3 on 2022-03-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_desription_review_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desciption',
            new_name='description',
        ),
    ]
