# Generated by Django 4.0.3 on 2022-03-12 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_desciption_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa883052-9a7a-4515-a76d-4ee529916f0d'), primary_key=True, serialize=False),
        ),
    ]
